name: proyectoryr
description: Proyecto de Automatización R&R

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # cupertino_icons: ^1.0.2
  provider: ^6.0.1
  intl: ^0.17.0
  nb_utils: ^4.5.2
  image_picker: ^0.8.4+11
  path_provider: ^2.0.9
  path: ^1.8.0
  http: ^0.13.4
  sqflite: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_typeahead: ^4.0.0
  signature: ^5.0.0
  get: ^4.6.1
  location: ^4.4.0
  collection: ^1.15.0
  flutter_barcode_scanner: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.1.1

flutter_native_splash:
  color: "#47634e"
  image: static/images/logo_b_g.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: Quicksand
      fonts:
        - asset: static/fonts/Quicksand-Regular.ttf

  assets:
    - static/images/
    - static/images/login/

flutter_icons:
  image_path: 'static/images/login/icono_app.png'
  android: true
  ios: true